/**
 * Module: features-index (FEATURE-INDEX-0909)
 * Purpose: Render creation order where the operator actually looks for it — the file
 *          tree. `aitri status` has shown `#N · created · verified` per feature since
 *          rc.2 (FEATURE-ORDER-0729), but an IDE's folder view sorts `features/`
 *          alphabetically and no Aitri surface lived there; the owner reported the gap
 *          twice from real use. `<features>/INDEX.md` is a DERIVED, gitignored, regenerated
 *          view: nothing is stored, nothing is renumbered, Aitri never reads it back.
 *
 * Why not a number in the directory name (the literal request, tombstoned in rc.2 and
 * again here): a frozen `007.` collides when two people create features on parallel
 * branches, lies about implementation order (creation ≠ verified), breaks the
 * `aitri feature <verb> <name>` grammar, and renames every consumer's directories.
 * Ids never encode order (ADR-074/081); order is presentation.
 *
 * Why gitignored rather than committed: a committed derived file conflicts on every
 * parallel feature creation — the mild form of the same branch-collision cost — and
 * carries no state. The IDE tree is the reported need; every session begins with
 * `aitri status`/`resume` (AGENTS.md), which regenerates it in any clone.
 *
 * ONE rule for creation order: `proposalOrder()` (lib/snapshot.js) — the same sequence
 * the status render and the next-action ladder use, so no surface can disagree.
 */

import fs   from 'node:fs';
import path from 'node:path';
import { featuresDir as resolveFeaturesDir, loadConfig, atomicWrite } from './state.js';
import { proposalOrder } from './snapshot.js';
import { formatVerifyCounts } from './verify-display.js';
import { ensureAitriGitignore } from './gitignore.js';

export const INDEX_BASENAME = 'INDEX.md';
/** First line of every index Aitri writes — the ownership marker. A file without it is the
 *  user's: never overwritten, never deleted (rc.12 adversarial D1/D2). */
export const INDEX_MARKER = '<!-- aitri:features-index — generated, do not edit -->';
// The pre-marker rc.12 draft wrote the H1 + "Generated by Aitri" blurb as its first lines
// (it reached one live project through the `npm i -g .` symlink before the marker existed)
// — recognized as ours so that file is refreshed, not frozen as "foreign".
const LEGACY_HEAD = '# Features — in creation order\n\n> Generated by Aitri';
const isOurs = text => typeof text === 'string' && (text.startsWith(INDEX_MARKER) || text.startsWith(LEGACY_HEAD));

/** Repo-root-relative ignore entry for this project's layout (`features/INDEX.md` or `aitri/features/INDEX.md`). */
export function featuresIndexIgnoreEntry(config) {
  const lr = config?.layoutRoot || '';
  return path.posix.join(lr, 'features', INDEX_BASENAME);
}

/**
 * Creation ordinals — `Map<scopeName, N>` for dated features, in proposalOrder sequence.
 * Undated (pre-createdAt) features get no ordinal. Shared with the status render so the
 * `#N` in the terminal and the `#N` in the tree are the same number by construction.
 */
export function creationOrdinals(pipelines) {
  const dated = proposalOrder(pipelines).filter(p => p.scopeType !== 'root' && p.createdAt);
  return new Map(dated.map((p, i) => [p.scopeName, i + 1]));
}

const day = iso => (typeof iso === 'string' && iso.length >= 10 ? iso.slice(0, 10) : '—');

/** Markdown for the index. Pure — takes the snapshot, returns the document (null when no features). */
export function renderFeaturesIndex(snapshot) {
  const features = proposalOrder(snapshot.pipelines).filter(p => p.scopeType === 'feature');
  if (!features.length) return null;
  const ordinals = creationOrdinals(snapshot.pipelines);
  const rows = features.map(f => {
    const ord      = ordinals.has(f.scopeName) ? String(ordinals.get(f.scopeName)) : '—';
    const approved = f.phases.filter(p => !p.optional && p.status === 'approved').length;
    let verify = '⬜ not run';
    if (f.verify.ran) {
      const counts = formatVerifyCounts(f.verify.summary).trim();
      verify = `${f.verify.passed ? '✅' : '❌'}${counts ? ' ' + counts : ''}`;
    }
    const verified = f.verify.ran && f.verify.ranAt ? day(f.verify.ranAt) : '—';
    return `| ${ord} | ${f.scopeName} | ${day(f.createdAt)} | ${approved}/5 | ${verify} | ${verified} |`;
  });
  return [
    INDEX_MARKER,
    '# Features — in creation order',
    '',
    '> Generated by Aitri from each feature\'s `createdAt`. **Do not edit** — regenerated by',
    '> `aitri status`, `aitri resume` and `aitri feature init`; Aitri never reads it back.',
    '> Gitignored (a derived view, not state). `#` is the order of creation; *Last verified* is',
    '> the last `verify-run` — the closest durable proxy for implementation order. Features',
    '> created before Aitri recorded `createdAt` have no ordinal and sort last.',
    '',
    '| # | Feature | Created | Phases | Verify | Last verified |',
    '|--:|---------|---------|-------:|--------|---------------|',
    ...rows,
    '',
  ].join('\n');
}

/** The features dir must resolve INSIDE the project — `layoutRoot` is hand-editable committed
 *  JSON (`..`, an absolute path) and this module deletes and writes at the resolved path. */
function featuresDirInside(dir, config) {
  const fdir = resolveFeaturesDir(dir, config);
  const rel  = path.relative(path.resolve(dir), path.resolve(fdir));
  if (!rel || rel.startsWith('..') || path.isAbsolute(rel)) return null;
  return fdir;
}

/**
 * Write (or refresh) `<features>/INDEX.md` for the project at `dir`. Rules, in order:
 *  - the features dir must be inside the project (a garbage `layoutRoot` → 'none');
 *  - never manufacture `features/` for a project without features;
 *  - a pre-existing INDEX.md WITHOUT the marker is the user's file: left alone ('foreign'),
 *    said once on stderr — never overwritten, never deleted;
 *  - no features left → remove the index only if it is ours;
 *  - the `.gitignore` entry is ensured whenever it is MISSING, BEFORE the file is written
 *    (a derived file that exists un-ignored is the exact cost ADR-089 rejects); if the
 *    ignore file cannot be updated, nothing is written ('skipped');
 *  - the write is atomic (tmp + rename) and only when the content changed.
 * Returns { path, action: 'created' | 'updated' | 'unchanged' | 'removed' | 'foreign' | 'skipped' | 'none' }.
 */
export function writeFeaturesIndex(dir, snapshot, { quiet = false } = {}) {
  const config  = loadConfig(dir);
  const fdir    = featuresDirInside(dir, config);
  if (!fdir) return { path: null, action: 'none' };
  const target  = path.join(fdir, INDEX_BASENAME);
  const say     = msg => { if (!quiet) process.stderr.write(`[aitri] ${msg}\n`); };
  const rel     = path.relative(dir, target);

  const prev = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null;
  if (prev !== null && !isOurs(prev)) {
    say(`${rel} exists and is not Aitri's (no marker) — left untouched; the creation-order index is not written`);
    return { path: target, action: 'foreign' };
  }

  const content = renderFeaturesIndex(snapshot);
  if (content === null) {
    if (prev !== null) { fs.unlinkSync(target); return { path: target, action: 'removed' }; }
    return { path: target, action: 'none' };
  }
  if (!fs.existsSync(fdir)) return { path: target, action: 'none' };   // never manufacture the dir
  if (prev === content) return { path: target, action: 'unchanged' };

  // Ignore BEFORE write, and whenever missing — not only on first creation.
  const entry = featuresIndexIgnoreEntry(config);
  let fix;
  try { fix = ensureAitriGitignore(dir, { extra: [entry] }); }
  catch (e) {
    say(`could not update .gitignore (${e.code || e.message}) — ${rel} not written, so no un-ignored derived file appears`);
    return { path: target, action: 'skipped' };
  }
  atomicWrite(target, content);
  if (prev !== null) return { path: target, action: 'updated' };
  say(`${rel} created — creation order for the file tree` +
      (fix.added.includes(entry) ? ' (and ignored in .gitignore: it is a derived view, not state)' : ''));
  return { path: target, action: 'created' };
}
