import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { runNode, runNodeOk } from "../smoke/helpers/cli-test-helpers.mjs";

function setupProject(tempDir) {
  runNodeOk(["init", "--non-interactive", "--yes"], { cwd: tempDir });
}

function writeDOCPolicy(tempDir, extraEntries = "") {
  const policyContent = `# Documentation Policy

## Permitted Files

| File | Purpose | Owner |
|------|---------|-------|
| \`docs/MANIFESTO.md\` | What Aitri is | Permanent |
| \`docs/architecture.md\` | How Aitri works | Permanent |
| \`docs/DOC_POLICY.md\` | This file | Permanent |
| \`docs/project.json\` | Generated by Aitri commands | Generated |
| \`docs/discovery/*.md\` | Generated by aitri discover | Generated |
| \`docs/plan/*.md\` | Generated by aitri plan | Generated |
${extraEntries}
`;
  fs.mkdirSync(path.join(tempDir, "docs"), { recursive: true });
  fs.writeFileSync(path.join(tempDir, "docs", "DOC_POLICY.md"), policyContent, "utf8");
}

test("DOC-POLICY check passes when all docs/ files are listed", () => {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "aitri-doc-policy-pass-"));
  setupProject(tempDir);
  writeDOCPolicy(tempDir);

  // Create only permitted files
  fs.writeFileSync(path.join(tempDir, "docs", "MANIFESTO.md"), "# Manifesto\n", "utf8");
  fs.writeFileSync(path.join(tempDir, "docs", "architecture.md"), "# Arch\n", "utf8");

  const result = runNode(["doctor", "--json"], { cwd: tempDir });
  const payload = JSON.parse(result.stdout);
  const check = payload.checks.find((c) => c.id === "DOC-POLICY");
  assert.ok(check, "DOC-POLICY check should be present");
  assert.equal(check.ok, true);
});

test("DOC-POLICY check fails when unlisted file exists in docs/", () => {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "aitri-doc-policy-fail-"));
  setupProject(tempDir);
  writeDOCPolicy(tempDir);

  // Create an unlisted file
  fs.writeFileSync(path.join(tempDir, "docs", "SCRATCH_phase99.md"), "# scratch\n", "utf8");

  const result = runNode(["doctor", "--json"], { cwd: tempDir });
  const payload = JSON.parse(result.stdout);
  const check = payload.checks.find((c) => c.id === "DOC-POLICY");
  assert.ok(check, "DOC-POLICY check should be present");
  assert.equal(check.ok, false);
  assert.ok(check.files.some((f) => f.includes("SCRATCH_phase99.md")));
  assert.ok(check.fix, "fix message should be present");
});

test("DOC-POLICY check passes for glob-matched generated files (discovery/*.md)", () => {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "aitri-doc-policy-glob-"));
  setupProject(tempDir);
  writeDOCPolicy(tempDir);

  // Create a generated file matching docs/discovery/*.md
  fs.mkdirSync(path.join(tempDir, "docs", "discovery"), { recursive: true });
  fs.writeFileSync(path.join(tempDir, "docs", "discovery", "user-auth.md"), "# Discovery\n", "utf8");

  const result = runNode(["doctor", "--json"], { cwd: tempDir });
  const payload = JSON.parse(result.stdout);
  const check = payload.checks.find((c) => c.id === "DOC-POLICY");
  assert.equal(check.ok, true);
});

test("DOC-POLICY check skips hidden files (e.g. .DS_Store)", () => {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "aitri-doc-policy-hidden-"));
  setupProject(tempDir);
  writeDOCPolicy(tempDir);

  // Create a hidden OS artifact — should not be flagged
  fs.writeFileSync(path.join(tempDir, "docs", ".DS_Store"), "", "utf8");

  const result = runNode(["doctor", "--json"], { cwd: tempDir });
  const payload = JSON.parse(result.stdout);
  const check = payload.checks.find((c) => c.id === "DOC-POLICY");
  assert.equal(check.ok, true);
});

test("DOC-POLICY check passes when no DOC_POLICY.md exists (no enforcement without policy)", () => {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "aitri-doc-policy-nopolicy-"));
  setupProject(tempDir);
  // Deliberately do NOT write DOC_POLICY.md

  const result = runNode(["doctor", "--json"], { cwd: tempDir });
  const payload = JSON.parse(result.stdout);
  const check = payload.checks.find((c) => c.id === "DOC-POLICY");
  assert.equal(check.ok, true, "no policy file = no enforcement");
});
